name: Deploy Website to Heroku
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            # effectue un Git clone
            - uses: actions/checkout@v2
            #linter
            - uses: michaelw90/PHP-Lint@master